### ISSUE TITLE
Cannot switch Parent App to Child App when use react-native-map

### ISSUE THREAD

**Issue by NguyenManh1404** [votrai123/integrate-multiple-react-native#1]
```
`import React from 'react';
import {
  Dimensions,
  NativeModules,
  SafeAreaView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import MapView, {Callout, Marker, PROVIDER_GOOGLE} from 'react-native-maps';
import AppInfo from './app.json';

const {height} = Dimensions.get('window');
const {ConnectNativeModule} = NativeModules;
const App = props => {
  return (
    <SafeAreaView>
      <View>
        <MapView
          provider={PROVIDER_GOOGLE}
          zoomControlEnabled={true}
          zoomEnabled={true}
          style={{
            height: height - 200,
          }}
          region={{
            latitude: 16.069560532577032,
            longitude: 108.23408695899637,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}>
          <Marker
            coordinate={{
              latitude: 16.069560532577032,
              longitude: 108.23408695899637,
            }}>
            <Callout>
              <Text>Address</Text>
            </Callout>
          </Marker>
        </MapView>
      </View>
      <View>
        <Text style={styles.title}>App One</Text>
        <Text style={styles.content}>
          Here props from super app: {JSON.stringify(props)}
        </Text>
        <TouchableOpacity
          style={styles.button}
          onPress={() => {
            ConnectNativeModule?.closeApp(AppInfo.name);
          }}>
          <Text style={styles.content}>Close App</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
};

export default App;


`
```

**Comment by votrai123** [comment]
Hi @NguyenManh1404 ,
1. Have you ensured that `react-native-screens` is installed in the supper and mini apps?
2. In the supper app, we also need to install the same library as the mini app? You need to install `react-native-maps` in the supper app
3. In the path `android/app/src/main/java/com/superapp/miniapp/MiniAppActivity.java`, line 60, you need to add the line `new MapsPackage()` to supper using lib
4. Finally, you rebuild the bundle file and rebuild the project
Thanks

**Comment by NguyenManh1404** [comment]
> Hi @NguyenManh1404 ,
> 
> 1. Have you ensured that `react-native-screens` is installed in the supper and mini apps?
> 2. In the supper app, we also need to install the same library as the mini app? You need to install `react-native-maps` in the supper app
> 3. In the path `android/app/src/main/java/com/superapp/miniapp/MiniAppActivity.java`, line 60, you need to add the line `new MapsPackage()` to supper using lib
> 4. Finally, you rebuild the bundle file and rebuild the project
>    Thanks

**Is not work** when done follow 4 step. APP continue crash when swich app
my repo: https://github.com/NguyenManh1404/switchApp

**Comment by votrai123** [comment]
Are you missing step 3?

**Comment by NguyenManh1404** [comment]
> 3\. new MapsPackage()

I can not import on android studio code , I think it auto link
<img width="697" alt="Screenshot 2023-11-08 at 15 48 19" src="https://github.com/votrai123/integrate-multiple-react-native/assets/74901875/6f0a7152-6ab9-4ad9-bcac-e9e5bbc17785">

**Comment by votrai123** [comment]
import from here!!
<img width="1141" alt="image" src="https://github.com/votrai123/integrate-multiple-react-native/assets/58043896/d99cdac2-e4fe-42f7-aa0f-01ac278e75a8">

**Comment by NguyenManh1404** [comment]
Why I can not import. Can you open this project on android studio code 
<img width="752" alt="Screenshot 2023-11-08 at 17 09 52" src="https://github.com/votrai123/integrate-multiple-react-native/assets/74901875/7ffab7a8-2f52-4d68-a698-dcb8c85874cc">

**Comment by votrai123** [comment]
In Android Studio. Have you synced Gradle yet?

**Comment by NguyenManh1404** [comment]
It works, many thanks @votrai123 . But it not work on IOS platform

**Comment by votrai123** [comment]
@NguyenManh1404 #3
