### ISSUE TITLE
Cannot use closeApp

### ISSUE THREAD

**Issue by hookie256** [votrai123/integrate-multiple-react-native#13]
I handle deeplink in superapp.
From MiniApp, I call a deeplink, deeplink open superapp, and I forward params to MiniApp by put it in openApp method from SuperApp
When MiniApp opened, I call closeApp method...but nothing happens, I cannot go back to superapp

**Comment by hookie256** [comment]
I found callback is null in closeApp function...so what I have to do now?

**Comment by hookie256** [comment]
@votrai123

**Comment by votrai123** [comment]
Could you please share the logs with me? @hookie256
