### ISSUE TITLE
index.ios-1.bundle how to generate?

### ISSUE THREAD

**Issue by NguyenManh1404** [votrai123/integrate-multiple-react-native#2]

**Comment by votrai123** [comment]
https://medium.com/@trai-nguyen/how-to-integrate-multiple-applications-with-react-native-275f13eb76d9
it is in this blog, hope it will help you @NguyenManh1404

**Comment by NguyenManh1404** [comment]
> https://medium.com/@trai-nguyen/how-to-integrate-multiple-applications-with-react-native-275f13eb76d9 it is in this blog, hope it will help you @NguyenManh1404

document for android only

**Comment by NguyenManh1404** [comment]
![Screenshot 2023-11-08 at 14 55 23](https://github.com/votrai123/integrate-multiple-react-native/assets/74901875/10612882-f391-4981-9810-a2b34577ee35)
How to generate on ios bunde @votrai123

**Comment by votrai123** [comment]
Please follow the next part of the blog, link at the bottom @NguyenManh1404

**Comment by NguyenManh1404** [comment]
Where the link, I need help for you

**Comment by votrai123** [comment]
related: https://medium.com/@trai-nguyen
