### ISSUE TITLE
error when install react-native-animated in mini app. 

### ISSUE THREAD

**Issue by hookie256** [votrai123/integrate-multiple-react-native#7]
**Describe the bug**
When I install react-native-animated in mini app, 
When from Parent app, I open Mini app, it appears blank screen and I found log 
[Reanimated] Native part of Reanimated doesn't seem to be initialized.
See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized for more details.
2023-12-20 14:47:04.675533+0700 SuperApp[10491:115272] [javascript] TypeError: undefined is not an object (evaluating 'r(d[4]).AnimatedView')

**Comment by votrai123** [comment]
Help me to detail the error correctly. (code, images, or steps ...) @hookie256

**Comment by hookie256** [comment]
Step 1: from Mini app, I install react-native-animated lib by this instruction: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/
Step 2: I run this command to export bundle file again: npx react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ../../ios/index.ios-1.bundle --assets-dest ../../ios/ --reset-cache
Step 3: I run yarn ios in Super App
The SuperApp runs, after that I click to MiniApp One button, and MiniApp One open, the blank screen appear, and I see this error in Xcode log
[Reanimated] Native part of Reanimated doesn't seem to be initialized.
See https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#native-part-of-reanimated-doesnt-seem-to-be-initialized for more details.
2023-12-20 14:47:04.675533+0700 SuperApp[10491:115272] [javascript] TypeError: undefined is not an object (evaluating 'r(d[4]).AnimatedView')

**Comment by hookie256** [comment]
https://github.com/votrai123/integrate-multiple-react-native/assets/60592878/9a2869e6-478f-4a87-91cc-b2b53a277600
![Screenshot 2023-12-20 at 15 13 37](https://github.com/votrai123/integrate-multiple-react-native/assets/60592878/e1e20377-3697-4cef-bb74-a1f1555f72b4)

**Comment by votrai123** [comment]
#3 #1
https://github.com/votrai123/integrate-multiple-react-native/issues/1#issuecomment-1801081984
It's the same as other issues
@hookie256

**Comment by hookie256** [comment]
Sorry, I missed some infomation,
SuperApp I install react native version 0.69
MiniApp I install react native version 0.71
I resolve error by your above comment, but this error appears
![Screenshot 2023-12-20 at 15 44 24](https://github.com/votrai123/integrate-multiple-react-native/assets/60592878/7033b5bf-fbe6-4257-a053-193e83907f96)

**Comment by hookie256** [comment]
So,Do MiniApp and SuperApp need the same react native version?

**Comment by votrai123** [comment]
You can use

https://react-native-community.github.io/upgrade-helper/?from=0.69.0&to=0.71.0
